# SonarCloud Configuration
sonar.projectKey=AlejandroPiresHerrera_movies-api-gate
sonar.organization=alejandropiresherrera

# Project metadata
sonar.projectName=Movies API Gate
sonar.projectVersion=1.0

# Source and test paths
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage report path
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/test/**,**/main.ts
sonar.coverage.exclusions=**/*.spec.ts,**/*.module.ts,**/main.ts,**/test/**

# Language
sonar.language=ts
